const ImageModule = {
  appIcon: require("../assets/Icons/appIcon.png"),

  // icons
  departIcon: require("../assets/Icons/inputTakeoff.png"),
  arrivalIcon: require("../assets/Icons/AirplaneLanding.png"),
  calendatIcon: require("../assets/Icons/Calender.png"),

  // class images
  business: require("../assets/Icons/business.png"),
  economy: require("../assets/Icons/economy.png"),
  peconomy: require("../assets/Icons/peconomy.png"),
  first: require("../assets/Icons/first.png"),
  google: require("../assets/Icons/Google.png"),
  plane: require("../assets/Icons/plane.png"),
  mytripplane: require("../assets/Icons/mytripplane.png"),
  Calendersecond: require("../assets/Icons/Calendersecond.png"),
  planemid: require("../assets/Icons/planemid.png"),
  clock: require("../assets/Icons/clock.png"),
  baggageIcon: require("../assets/Icons/baggageIcon.png"),
  carryOnIcon: require("../assets/Icons/carryOnIcon.png"),
  refreshIcon: require("../assets/Icons/refreshIcon.png"),
  filterIcon: require("../assets/Icons/filter.png"),
  sortIcon: require("../assets/Icons/sort.png"),
  airplaneTakeoff: require("../assets/Icons/airplaneTakeoff.png"),
  transitIcon: require("../assets/Icons/transitIcon.png"),
  lineIcon: require("../assets/Icons/line.png"),
  dummyLogo: require("../assets/Icons/dummylogo.png"),
  checkIcon: require("../assets/Icons/checkIcon.png"),
  eye_open: require("../assets/Icons/eye_open.png"),
  eye_close: require("../assets/Icons/eye_close.png"),
  profile_bg: require("../assets/Icons/profile_bg.png"),
  mic: require("../assets/Icons/mic.png"),
  settings: require("../assets/Icons/settings.png"),
  aboutus: require("../assets/Icons/aboutus.png"),
  addUser: require("../assets/Icons/addUser.png"),
  my_account: require("../assets/Icons/my_account.png"),
  manage_trip: require("../assets/Icons/manage_trip.png"),
  logout: require("../assets/Icons/logout.png"),
  protection: require("../assets/Icons/protection.png"),
  circleplane: require("../assets/Icons/circleplane.png"),
  placeanimation: require("../assets/Icons/placeanimation.gif"),
};

export default ImageModule;
